### ISSUE TITLE
Dependency on Optional Embree backend

### ISSUE THREAD

**Issue by bl33m** [uos/radarays_ros#1]
![Screenshot from 2024-01-31 13-53-37](https://github.com/uos/radarays_ros/assets/66042567/63539749-c2f2-41ff-a989-b786335b01dc)

I was able to install and have verified that optix and rmagine are working properly. It seems as though embree is still a mandatory dependency for some packages as I am getting the following errors when I try to build. Please let me know if there is some configuration setting I am missing to only build the GPU support. Thanks!

**Comment by amock** [comment]
Hi Blerim!

ah yes, that's wrong. Thanks for figuring it out :) The quickest thing you can do is to install embree. Then it will compile, but it won't be used once you enable the GPU implementation. The bug is just that some parts of the code and the cmake are requiring it. My first try to fix it I just pushed on the branch "fix/optional-embree". Could you try out if this branch compiles without embree?

Greetings
Alex

**Comment by bl33m** [comment]
Thanks for the speedy reply!

I was able to get the project to build and run the gazebo demo with the radar. I took embree away from my docker container and I was able to get the package to build after commenting out line 120 in the CMakelists.txt. However the plugin does not seem to be loading after I get the following output from gazebo after running the demo script.

![image](https://github.com/uos/radarays_ros/assets/66042567/22ca8430-b26a-4199-9aae-50035bfd5590)

**Comment by amock** [comment]
ah yes, I missed that one. Now it should be fixed. Back to your new errors. They are both coming from the [radarays_gazebo_plugins](https://github.com/uos/radarays_gazebo_plugins) package:

1. Gazebo Plugin
```console
[Err] [Plugin.hh:212] Failed to load plugin libradarays_embree_sensors_gzregister.so: librmagine-embree.so.2: cannot open...
```

Once you removed embree, some things in your ROS workspace still exist linking to missing embree stuff. Making a fresh recompilation of your ROS workspace should fix the linker error to the missing librmagine-embree.so. Afterwards the following error should pop up instead:

```console
[Err] [Plugin.hh:212] Failed to load plugin libradarays_embree_sensors_gzregister.so: libradarays_embree_sensors_gzregister.so: cannot open shared object file: No such file or directory
...
[Err] [Plugin.hh:212] Failed to load plugin librmagine_embree_map_gzplugin.so: librmagine_embree_map_gzplugin.so: cannot open shared object file: No such file or directory
```

but that's ok. It should not cause the Gazebo to crash as long as you are only using the GPU implementation. If you are annoyed of that message, remove "-s libradarays_embree_sensors_gzregister.so" from `example_robot.launch` and the embree map thing from the world file.

2. CUDA runtime error

I'm a bit surprised of that one. I just removed embree completely from my system and made a fresh reinstallation of everything that was depending on it. And had no errors causing Gazebo to crash. Nor any CUDA errors. I hope the error vanishes once you do a fresh install of everything. Otherwise, here is my setup to compare:

I started the example via
```console
roslaunch radarays_gazebo_plugins example_robot.launch rmagine:=optix 
```

my system:
- Ubuntu 20.04
- (No embree)
- NVIDIA Driver Version: 470.223.02
- CUDA Driver Version / Runtime Version: 11.4.0 / 11.4.0
- OptiX 7.3
- rmagine 2.2.2: compiled components: core, cuda, optix
- ROS - noetic
- Gazebo 11.9.1
- radarays_ros (branch: fix/optional-embree)
- radarays_gazebo_plugins (branch: main)

If things are still not working. Maybe you can write me your setup, so that I can better try to reproduce your errors.

**Comment by amock** [comment]
With merging the PR this issue is closed for now. Let me know if things are still not working

**Comment by bl33m** [comment]
Thanks for the help on this!
